## MULTIPLE LINEAR REGRESSION IMPLEMENTATION USING SCIKITLEARN

In [2]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go 
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
x,y = make_regression(n_samples = 100, n_features=2, n_informative=2, n_targets=1,noise =50)

In [4]:
df = pd.DataFrame({'feature1':x[:,0],'feature2':x[:,1],'target':y})

In [5]:
df.shape

(100, 3)

In [6]:
df.head()

feature1  feature2     target
0  0.356193 -0.569822 -56.522787
1 -0.057240 -0.858677 -45.501787
2 -0.928125 -0.089270  -3.489224
3 -0.401899  0.541585  22.226760
4 -0.010314 -0.353909 -37.389985

In [7]:
fig = px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.show()

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =  train_test_split(x,y,test_size=0.2,random_state=3)
from sklearn.linear_model import LinearRegression

In [10]:
lr = LinearRegression()

In [11]:
lr.fit(x_train,y_train)

LinearRegression()

In [14]:
LinearRegression(copy_X = True, fit_intercept=True,n_jobs=None)

LinearRegression()

In [15]:
y_pred = lr.predict(x_test)

In [16]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 41.04256586476648
MSE 2775.5427806640428
R2 score 0.7611798748271299


In [ ]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

final = np.vstack((
    xGrid.ravel().reshape(1, 100),
    yGrid.ravel().reshape(1, 100)
)).T

z_final = lr.predict(final).reshape(10, 10)
z = z_final

In [20]:
fig =px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.add_trace(go.Surface(x=x,y=y,z=z))
fig.show()

In [21]:
lr.coef_

array([27.31023936, 73.18301639])

In [22]:
lr.intercept_

np.float64(2.6203884856638577)

## MAKING OUR OWN LINEAR REGRESSION CLASS

In [38]:
class MeraLR:
    def __init__(self):
        self.coefficients = None
        self.intercept = None
    def fit(self, x, y):
       x_transformed = np.insert(x_train,0,1,axis=1)
       #calculate coefficients 
       betas = np.linalg.inv(x_transformed.T @ x_transformed) @ x_transformed.T @ y
       self.intercept = betas[0]
       self.coefficients = betas[1:]
       print(betas)
    def predict(self, x_test):
        y_pred = np.dot(x_test,self.coefficients)+self.intercept
        return y_pred

In [39]:
lr=MeraLR()

In [40]:
lr.fit(x_train,y_train)

[ 2.62038849 27.31023936 73.18301639]


In [41]:
x_train.shape

(80, 2)

In [42]:
np.insert(x_train,0,1,axis=1).shape

(80, 3)

In [43]:
lr.predict(x_test)

array([205.73452852, -54.19289356, -18.63774353, -60.43912194,
       -47.73203706, 133.4565087 , -30.63985993, 109.02112836,
        89.2391186 ,  35.41390382,  48.23290159,  30.76446576,
       -24.82627932,  95.06701549,  69.45924269, -54.15127131,
       -90.97917253,  86.10676805, -95.09266027, -97.9525071 ])

In [44]:
r2_score(y_test,y_pred)

0.7611798748271299

In [46]:
lr.coefficients

array([27.31023936, 73.18301639])

In [47]:
lr.intercept

np.float64(2.620388485663859)